spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/social_db
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update

minio:
  url: http://localhost:9000
