package com.reveria.userservice.model.enums;

public enum UserEventType {
    USER_REGISTERED,
    USER_LOGGED_IN,
    USER_EMAIL_VERIFIED,
    USER_PROFILE_UPDATED,
    USER_AVATAR_UPDATED,
    USER_AVATAR_DELETED,
    USER_PRIVACY_UPDATED,
    USER_DEACTIVATED,
    USER_PASSWORD_CHANGED,
    USER_OAUTH_LINKED,
    USER_OAUTH_UNLINKED,
    USER_STATUS_CHANGED
}
