spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/content_db
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

storage:
  minio:
    endpoint: http://localhost:9000

livestream:
  rtmp-host: 192.168.11.110
  rtmp-port: 1935
  hls-base-url: http://192.168.11.110:8088/hls
